#pragma once
#include <GL/glew.h>
#include <GLFW/glfw3.h>

namespace gfm
{
namespace input
{
	enum class KeyboardAction{
		eACTION_PRESS   = GLFW_PRESS,
		eACTION_REPEAT  = GLFW_REPEAT,
		eACTION_RELEASE = GLFW_RELEASE
	};

	enum class KeyboardKey{
		eKEY_SPACE         = GLFW_KEY_SPACE,
		eKEY_APOSTROPHE    = GLFW_KEY_APOSTROPHE,
		eKEY_COMMA         = GLFW_KEY_COMMA,
		eKEY_MINUS         = GLFW_KEY_MINUS,
		eKEY_PERIOD		   = GLFW_KEY_PERIOD,
		eKEY_SLASH		   = GLFW_KEY_SLASH,
		eKEY_0			   = GLFW_KEY_0,
		eKEY_1			   = GLFW_KEY_1,
		eKEY_2			   = GLFW_KEY_2,
		eKEY_3			   = GLFW_KEY_3,
		eKEY_4			   = GLFW_KEY_4,
		eKEY_5			   = GLFW_KEY_5,
		eKEY_6			   = GLFW_KEY_6,
		eKEY_7			   = GLFW_KEY_7,
		eKEY_8			   = GLFW_KEY_8,
		eKEY_9			   = GLFW_KEY_9,
		eKEY_SEMICOLON	   = GLFW_KEY_SEMICOLON,
		eKEY_EQUAL		   = GLFW_KEY_EQUAL,
		eKEY_A			   = GLFW_KEY_A,
		eKEY_B			   = GLFW_KEY_B,
		eKEY_C			   = GLFW_KEY_C,
		eKEY_D			   = GLFW_KEY_D,
		eKEY_E			   = GLFW_KEY_E,
		eKEY_F			   = GLFW_KEY_F,
		eKEY_G			   = GLFW_KEY_G,
		eKEY_H			   = GLFW_KEY_H,
		eKEY_I			   = GLFW_KEY_I,
		eKEY_J			   = GLFW_KEY_J,
		eKEY_K			   = GLFW_KEY_K,
		eKEY_L			   = GLFW_KEY_L,
		eKEY_M			   = GLFW_KEY_M,
		eKEY_N			   = GLFW_KEY_N,
		eKEY_O			   = GLFW_KEY_O,
		eKEY_P			   = GLFW_KEY_P,
		eKEY_Q			   = GLFW_KEY_Q,
		eKEY_R			   = GLFW_KEY_R,
		eKEY_S			   = GLFW_KEY_S,
		eKEY_T			   = GLFW_KEY_T,
		eKEY_U			   = GLFW_KEY_U,
		eKEY_V			   = GLFW_KEY_V,
		eKEY_W			   = GLFW_KEY_W,
		eKEY_X			   = GLFW_KEY_X,
		eKEY_Y			   = GLFW_KEY_Y,
		eKEY_Z			   = GLFW_KEY_Z,
		eKEY_LEFT_BRACKET  = GLFW_KEY_LEFT_BRACKET,
		eKEY_BACKSLAH	   = GLFW_KEY_BACKSLASH,
		eKEY_RIGHT_BRACKET = GLFW_KEY_RIGHT_BRACKET,
		eKEY_GRAVE_ACCENT  = GLFW_KEY_GRAVE_ACCENT,
		eKEY_WORLD_1	   = GLFW_KEY_WORLD_1,
		eKEY_WORLD_2	   = GLFW_KEY_WORLD_2,
		eKEY_ESCAPE		   = GLFW_KEY_ESCAPE,     
		eKEY_ENTER		   = GLFW_KEY_ENTER,        
		eKEY_TAB		   = GLFW_KEY_TAB,           
		eKEY_BACKSAPE	   = GLFW_KEY_BACKSPACE,     
		eKEY_INSERT		   = GLFW_KEY_INSERT,       
		eKEY_DELETE		   = GLFW_KEY_DELETE,        
		eKEY_RIGHT		   = GLFW_KEY_RIGHT,        
		eKEY_LEFT		   = GLFW_KEY_LEFT,          
		eKEY_DOWN		   = GLFW_KEY_DOWN,          
		eKEY_UP			   = GLFW_KEY_UP,            
		eKEY_PAGE_UP	   = GLFW_KEY_PAGE_UP,       
		eKEY_PAGE_DOWN	   = GLFW_KEY_PAGE_DOWN,     
		eKEY_HOME		   = GLFW_KEY_HOME,          
		eKEY_END		   = GLFW_KEY_END,           
		eKEY_CAPS_LOCK	   = GLFW_KEY_CAPS_LOCK,     
		eKEY_SCROLL_LOCK   = GLFW_KEY_SCROLL_LOCK,   
		eKEY_NUM_lOCK	   = GLFW_KEY_NUM_LOCK,     
		eKEY_PRINT_SCREEN  = GLFW_KEY_PRINT_SCREEN , 
		eKEY_PAUSE		   = GLFW_KEY_PAUSE,         
		eKEY_F1			   = GLFW_KEY_F1,            
		eKEY_F2			   = GLFW_KEY_F2,            
		eKEY_F3			   = GLFW_KEY_F3,            
		eKEY_F4			   = GLFW_KEY_F4,            
		eKEY_F5			   = GLFW_KEY_F5,            
		eKEY_F6			   = GLFW_KEY_F6,            
		eKEY_F7			   = GLFW_KEY_F7,            
		eKEY_F8			   = GLFW_KEY_F8,            
		eKEY_F9			   = GLFW_KEY_F9,            
		eKEY_F10		   = GLFW_KEY_F10,           
		eKEY_F11		   = GLFW_KEY_F11,           
		eKEY_F12		   = GLFW_KEY_F12,           
		eKEY_F13		   = GLFW_KEY_F13,           
		eKEY_F14		   = GLFW_KEY_F14,           
		eKEY_F15		   = GLFW_KEY_F15,           
		eKEY_F16		   = GLFW_KEY_F16,           
		eKEY_F17		   = GLFW_KEY_F17,           
		eKEY_F18		   = GLFW_KEY_F18,           
		eKEY_F19		   = GLFW_KEY_F19,           
		eKEY_F20		   = GLFW_KEY_F20,           
		eKEY_F21		   = GLFW_KEY_F21,           
		eKEY_F22		   = GLFW_KEY_F22,           
		eKEY_F23		   = GLFW_KEY_F23,           
		eKEY_F24		   = GLFW_KEY_F24,           
		eKEY_F25		   = GLFW_KEY_F25,           
		eKEY_KP_0		   = GLFW_KEY_KP_0,          
		eKEY_KP_1		   = GLFW_KEY_KP_1,          
		eKEY_KP_2		   = GLFW_KEY_KP_2,          
		eKEY_KP_3		   = GLFW_KEY_KP_3,          
		eKEY_KP_4		   = GLFW_KEY_KP_4,          
		eKEY_KP_5		   = GLFW_KEY_KP_5,          
		eKEY_KP_6		   = GLFW_KEY_KP_6,          
		eKEY_KP_7		   = GLFW_KEY_KP_7,          
		eKEY_KP_8		   = GLFW_KEY_KP_8,          
		eKEY_KP_9		   = GLFW_KEY_KP_9,          
		eKEY_KP_DECIMAL	   = GLFW_KEY_KP_DECIMAL,   
		eKEY_KP_DIVIDE	   = GLFW_KEY_KP_DIVIDE,    
		eKEY_KP_MULTIPLY   = GLFW_KEY_KP_MULTIPLY,   
		eKEY_KP_SUBTRACT   = GLFW_KEY_KP_SUBTRACT,   
		eKEY_KP_ADD		   = GLFW_KEY_KP_ADD,        
		eKEY_KP_ENTER	   = GLFW_KEY_KP_ENTER,      
		eKEY_KP_EQUAL	   = GLFW_KEY_KP_EQUAL,      
		eKEY_LEFT_SHIFT	   = GLFW_KEY_LEFT_SHIFT,    
		eKEY_LEFT_CONTROL  = GLFW_KEY_LEFT_CONTROL,  
		eKEY_LEFT_ALT	   = GLFW_KEY_LEFT_ALT,      
		eKEY_LEFT_SUPER	   = GLFW_KEY_LEFT_SUPER,    
		eKEY_RIGHT_SHIFT   = GLFW_KEY_RIGHT_SHIFT,   
		eKEY_RIGHT_CONTROL = GLFW_KEY_RIGHT_CONTROL, 
		eKEY_RIGHT_ALT	   = GLFW_KEY_RIGHT_ALT,     
		eKEY_RIGHT_SUPER   = GLFW_KEY_RIGHT_SUPER,   
		eKEY_MENU		   = GLFW_KEY_MENU,
		eKEY_MAX		   = GLFW_KEY_LAST
	};
}
}
